// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: proto/guardv1/guard.proto

package guardv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuleType int32

const (
	RuleType_RULE_TYPE_UNSPECIFIED            RuleType = 0
	RuleType_RULE_TYPE_IMPOSSIBLE_TRAVEL      RuleType = 1
	RuleType_RULE_TYPE_SIMULTANEOUS_LOCATIONS RuleType = 2
	RuleType_RULE_TYPE_DEVICE_VELOCITY        RuleType = 3
	RuleType_RULE_TYPE_CONCURRENT_STREAMS     RuleType = 4
	RuleType_RULE_TYPE_GEO_RESTRICTION        RuleType = 5
	RuleType_RULE_TYPE_ACCOUNT_INACTIVITY     RuleType = 6
)

// Enum value maps for RuleType.
var (
	RuleType_name = map[int32]string{
		0: "RULE_TYPE_UNSPECIFIED",
		1: "RULE_TYPE_IMPOSSIBLE_TRAVEL",
		2: "RULE_TYPE_SIMULTANEOUS_LOCATIONS",
		3: "RULE_TYPE_DEVICE_VELOCITY",
		4: "RULE_TYPE_CONCURRENT_STREAMS",
		5: "RULE_TYPE_GEO_RESTRICTION",
		6: "RULE_TYPE_ACCOUNT_INACTIVITY",
	}
	RuleType_value = map[string]int32{
		"RULE_TYPE_UNSPECIFIED":            0,
		"RULE_TYPE_IMPOSSIBLE_TRAVEL":      1,
		"RULE_TYPE_SIMULTANEOUS_LOCATIONS": 2,
		"RULE_TYPE_DEVICE_VELOCITY":        3,
		"RULE_TYPE_CONCURRENT_STREAMS":     4,
		"RULE_TYPE_GEO_RESTRICTION":        5,
		"RULE_TYPE_ACCOUNT_INACTIVITY":     6,
	}
)

func (x RuleType) Enum() *RuleType {
	p := new(RuleType)
	*p = x
	return p
}

func (x RuleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_guardv1_guard_proto_enumTypes[0].Descriptor()
}

func (RuleType) Type() protoreflect.EnumType {
	return &file_proto_guardv1_guard_proto_enumTypes[0]
}

func (x RuleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleType.Descriptor instead.
func (RuleType) EnumDescriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{0}
}

type GuardRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          RuleType               `protobuf:"varint,2,opt,name=type,proto3,enum=muxcore.playback.guard.v1.RuleType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Params        map[string]string      `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardRule) Reset() {
	*x = GuardRule{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardRule) ProtoMessage() {}

func (x *GuardRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardRule.ProtoReflect.Descriptor instead.
func (*GuardRule) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{0}
}

func (x *GuardRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GuardRule) GetType() RuleType {
	if x != nil {
		return x.Type
	}
	return RuleType_RULE_TYPE_UNSPECIFIED
}

func (x *GuardRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GuardRule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GuardRule) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type Violation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleId        string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RuleType      RuleType               `protobuf:"varint,3,opt,name=rule_type,json=ruleType,proto3,enum=muxcore.playback.guard.v1.RuleType" json:"rule_type,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,5,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Summary       string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	Severity      string                 `protobuf:"bytes,7,opt,name=severity,proto3" json:"severity,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,8,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	Acknowledged  bool                   `protobuf:"varint,9,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Violation) Reset() {
	*x = Violation{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Violation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Violation) ProtoMessage() {}

func (x *Violation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Violation.ProtoReflect.Descriptor instead.
func (*Violation) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{1}
}

func (x *Violation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Violation) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Violation) GetRuleType() RuleType {
	if x != nil {
		return x.RuleType
	}
	return RuleType_RULE_TYPE_UNSPECIFIED
}

func (x *Violation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Violation) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Violation) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Violation) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Violation) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Violation) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type ListRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesRequest) Reset() {
	*x = ListRulesRequest{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesRequest) ProtoMessage() {}

func (x *ListRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesRequest.ProtoReflect.Descriptor instead.
func (*ListRulesRequest) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{2}
}

type ListRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*GuardRule           `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesResponse) Reset() {
	*x = ListRulesResponse{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesResponse) ProtoMessage() {}

func (x *ListRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesResponse.ProtoReflect.Descriptor instead.
func (*ListRulesResponse) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{3}
}

func (x *ListRulesResponse) GetRules() []*GuardRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type UpsertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *GuardRule             `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRuleRequest) Reset() {
	*x = UpsertRuleRequest{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRuleRequest) ProtoMessage() {}

func (x *UpsertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRuleRequest.ProtoReflect.Descriptor instead.
func (*UpsertRuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertRuleRequest) GetRule() *GuardRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type UpsertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *GuardRule             `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRuleResponse) Reset() {
	*x = UpsertRuleResponse{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRuleResponse) ProtoMessage() {}

func (x *UpsertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRuleResponse.ProtoReflect.Descriptor instead.
func (*UpsertRuleResponse) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertRuleResponse) GetRule() *GuardRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type DeleteRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleRequest) Reset() {
	*x = DeleteRuleRequest{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleRequest) ProtoMessage() {}

func (x *DeleteRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleResponse) Reset() {
	*x = DeleteRuleResponse{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleResponse) ProtoMessage() {}

func (x *DeleteRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRuleResponse) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRuleResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListViolationsRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IncludeAcknowledged bool                   `protobuf:"varint,1,opt,name=include_acknowledged,json=includeAcknowledged,proto3" json:"include_acknowledged,omitempty"`
	Limit               int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListViolationsRequest) Reset() {
	*x = ListViolationsRequest{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListViolationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListViolationsRequest) ProtoMessage() {}

func (x *ListViolationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListViolationsRequest.ProtoReflect.Descriptor instead.
func (*ListViolationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{8}
}

func (x *ListViolationsRequest) GetIncludeAcknowledged() bool {
	if x != nil {
		return x.IncludeAcknowledged
	}
	return false
}

func (x *ListViolationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListViolationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Violations    []*Violation           `protobuf:"bytes,1,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListViolationsResponse) Reset() {
	*x = ListViolationsResponse{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListViolationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListViolationsResponse) ProtoMessage() {}

func (x *ListViolationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListViolationsResponse.ProtoReflect.Descriptor instead.
func (*ListViolationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{9}
}

func (x *ListViolationsResponse) GetViolations() []*Violation {
	if x != nil {
		return x.Violations
	}
	return nil
}

type AcknowledgeViolationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViolationIds  []string               `protobuf:"bytes,1,rep,name=violation_ids,json=violationIds,proto3" json:"violation_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeViolationsRequest) Reset() {
	*x = AcknowledgeViolationsRequest{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeViolationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeViolationsRequest) ProtoMessage() {}

func (x *AcknowledgeViolationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeViolationsRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeViolationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{10}
}

func (x *AcknowledgeViolationsRequest) GetViolationIds() []string {
	if x != nil {
		return x.ViolationIds
	}
	return nil
}

type AcknowledgeViolationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       int32                  `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeViolationsResponse) Reset() {
	*x = AcknowledgeViolationsResponse{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeViolationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeViolationsResponse) ProtoMessage() {}

func (x *AcknowledgeViolationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeViolationsResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeViolationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{11}
}

func (x *AcknowledgeViolationsResponse) GetUpdated() int32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

type TerminateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServerType    string                 `protobuf:"bytes,2,opt,name=server_type,json=serverType,proto3" json:"server_type,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateSessionRequest) Reset() {
	*x = TerminateSessionRequest{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateSessionRequest) ProtoMessage() {}

func (x *TerminateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateSessionRequest.ProtoReflect.Descriptor instead.
func (*TerminateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{12}
}

func (x *TerminateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminateSessionRequest) GetServerType() string {
	if x != nil {
		return x.ServerType
	}
	return ""
}

func (x *TerminateSessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TerminateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateSessionResponse) Reset() {
	*x = TerminateSessionResponse{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateSessionResponse) ProtoMessage() {}

func (x *TerminateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateSessionResponse.ProtoReflect.Descriptor instead.
func (*TerminateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{13}
}

func (x *TerminateSessionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TerminateSessionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TrustScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,4,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustScore) Reset() {
	*x = TrustScore{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustScore) ProtoMessage() {}

func (x *TrustScore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustScore.ProtoReflect.Descriptor instead.
func (*TrustScore) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{14}
}

func (x *TrustScore) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TrustScore) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *TrustScore) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *TrustScore) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type GetTrustScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrustScoreRequest) Reset() {
	*x = GetTrustScoreRequest{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrustScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrustScoreRequest) ProtoMessage() {}

func (x *GetTrustScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrustScoreRequest.ProtoReflect.Descriptor instead.
func (*GetTrustScoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{15}
}

func (x *GetTrustScoreRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTrustScoreRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type GetTrustScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         *TrustScore            `protobuf:"bytes,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrustScoreResponse) Reset() {
	*x = GetTrustScoreResponse{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrustScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrustScoreResponse) ProtoMessage() {}

func (x *GetTrustScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrustScoreResponse.ProtoReflect.Descriptor instead.
func (*GetTrustScoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{16}
}

func (x *GetTrustScoreResponse) GetScore() *TrustScore {
	if x != nil {
		return x.Score
	}
	return nil
}

type ListTrustScoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrustScoresRequest) Reset() {
	*x = ListTrustScoresRequest{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrustScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrustScoresRequest) ProtoMessage() {}

func (x *ListTrustScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrustScoresRequest.ProtoReflect.Descriptor instead.
func (*ListTrustScoresRequest) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{17}
}

func (x *ListTrustScoresRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListTrustScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*TrustScore          `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrustScoresResponse) Reset() {
	*x = ListTrustScoresResponse{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrustScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrustScoresResponse) ProtoMessage() {}

func (x *ListTrustScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrustScoresResponse.ProtoReflect.Descriptor instead.
func (*ListTrustScoresResponse) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{18}
}

func (x *ListTrustScoresResponse) GetScores() []*TrustScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

type ResetTrustScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetTrustScoreRequest) Reset() {
	*x = ResetTrustScoreRequest{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetTrustScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetTrustScoreRequest) ProtoMessage() {}

func (x *ResetTrustScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetTrustScoreRequest.ProtoReflect.Descriptor instead.
func (*ResetTrustScoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{19}
}

func (x *ResetTrustScoreRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResetTrustScoreRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type ResetTrustScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         *TrustScore            `protobuf:"bytes,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetTrustScoreResponse) Reset() {
	*x = ResetTrustScoreResponse{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetTrustScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetTrustScoreResponse) ProtoMessage() {}

func (x *ResetTrustScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetTrustScoreResponse.ProtoReflect.Descriptor instead.
func (*ResetTrustScoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{20}
}

func (x *ResetTrustScoreResponse) GetScore() *TrustScore {
	if x != nil {
		return x.Score
	}
	return nil
}

type MergeUsersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceUserId   string                 `protobuf:"bytes,1,opt,name=source_user_id,json=sourceUserId,proto3" json:"source_user_id,omitempty"`
	SourceUserName string                 `protobuf:"bytes,2,opt,name=source_user_name,json=sourceUserName,proto3" json:"source_user_name,omitempty"`
	TargetUserId   string                 `protobuf:"bytes,3,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	TargetUserName string                 `protobuf:"bytes,4,opt,name=target_user_name,json=targetUserName,proto3" json:"target_user_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MergeUsersRequest) Reset() {
	*x = MergeUsersRequest{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeUsersRequest) ProtoMessage() {}

func (x *MergeUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeUsersRequest.ProtoReflect.Descriptor instead.
func (*MergeUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{21}
}

func (x *MergeUsersRequest) GetSourceUserId() string {
	if x != nil {
		return x.SourceUserId
	}
	return ""
}

func (x *MergeUsersRequest) GetSourceUserName() string {
	if x != nil {
		return x.SourceUserName
	}
	return ""
}

func (x *MergeUsersRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *MergeUsersRequest) GetTargetUserName() string {
	if x != nil {
		return x.TargetUserName
	}
	return ""
}

type MergeUsersResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ViolationsUpdated int32                  `protobuf:"varint,1,opt,name=violations_updated,json=violationsUpdated,proto3" json:"violations_updated,omitempty"`
	AliasesCreated    int32                  `protobuf:"varint,2,opt,name=aliases_created,json=aliasesCreated,proto3" json:"aliases_created,omitempty"`
	SessionsUpdated   int32                  `protobuf:"varint,3,opt,name=sessions_updated,json=sessionsUpdated,proto3" json:"sessions_updated,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MergeUsersResponse) Reset() {
	*x = MergeUsersResponse{}
	mi := &file_proto_guardv1_guard_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeUsersResponse) ProtoMessage() {}

func (x *MergeUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guardv1_guard_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeUsersResponse.ProtoReflect.Descriptor instead.
func (*MergeUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_guardv1_guard_proto_rawDescGZIP(), []int{22}
}

func (x *MergeUsersResponse) GetViolationsUpdated() int32 {
	if x != nil {
		return x.ViolationsUpdated
	}
	return 0
}

func (x *MergeUsersResponse) GetAliasesCreated() int32 {
	if x != nil {
		return x.AliasesCreated
	}
	return 0
}

func (x *MergeUsersResponse) GetSessionsUpdated() int32 {
	if x != nil {
		return x.SessionsUpdated
	}
	return 0
}

var File_proto_guardv1_guard_proto protoreflect.FileDescriptor

const file_proto_guardv1_guard_proto_rawDesc = "" +
	"\n" +
	"\x19proto/guardv1/guard.proto\x12\x19muxcore.playback.guard.v1\"\x87\x02\n" +
	"\tGuardRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\x04type\x18\x02 \x01(\x0e2#.muxcore.playback.guard.v1.RuleTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12H\n" +
	"\x06params\x18\x05 \x03(\v20.muxcore.playback.guard.v1.GuardRule.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x02\n" +
	"\tViolation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\x12@\n" +
	"\trule_type\x18\x03 \x01(\x0e2#.muxcore.playback.guard.v1.RuleTypeR\bruleType\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x05 \x01(\tR\buserName\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x12\x1a\n" +
	"\bseverity\x18\a \x01(\tR\bseverity\x12&\n" +
	"\x0fcreated_at_unix\x18\b \x01(\x03R\rcreatedAtUnix\x12\"\n" +
	"\facknowledged\x18\t \x01(\bR\facknowledged\"\x12\n" +
	"\x10ListRulesRequest\"O\n" +
	"\x11ListRulesResponse\x12:\n" +
	"\x05rules\x18\x01 \x03(\v2$.muxcore.playback.guard.v1.GuardRuleR\x05rules\"M\n" +
	"\x11UpsertRuleRequest\x128\n" +
	"\x04rule\x18\x01 \x01(\v2$.muxcore.playback.guard.v1.GuardRuleR\x04rule\"N\n" +
	"\x12UpsertRuleResponse\x128\n" +
	"\x04rule\x18\x01 \x01(\v2$.muxcore.playback.guard.v1.GuardRuleR\x04rule\"#\n" +
	"\x11DeleteRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12DeleteRuleResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"`\n" +
	"\x15ListViolationsRequest\x121\n" +
	"\x14include_acknowledged\x18\x01 \x01(\bR\x13includeAcknowledged\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"^\n" +
	"\x16ListViolationsResponse\x12D\n" +
	"\n" +
	"violations\x18\x01 \x03(\v2$.muxcore.playback.guard.v1.ViolationR\n" +
	"violations\"C\n" +
	"\x1cAcknowledgeViolationsRequest\x12#\n" +
	"\rviolation_ids\x18\x01 \x03(\tR\fviolationIds\"9\n" +
	"\x1dAcknowledgeViolationsResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\x05R\aupdated\"q\n" +
	"\x17TerminateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vserver_type\x18\x02 \x01(\tR\n" +
	"serverType\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"@\n" +
	"\x18TerminateSessionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x80\x01\n" +
	"\n" +
	"TrustScore\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12&\n" +
	"\x0fupdated_at_unix\x18\x04 \x01(\x03R\rupdatedAtUnix\"L\n" +
	"\x14GetTrustScoreRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\"T\n" +
	"\x15GetTrustScoreResponse\x12;\n" +
	"\x05score\x18\x01 \x01(\v2%.muxcore.playback.guard.v1.TrustScoreR\x05score\".\n" +
	"\x16ListTrustScoresRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"X\n" +
	"\x17ListTrustScoresResponse\x12=\n" +
	"\x06scores\x18\x01 \x03(\v2%.muxcore.playback.guard.v1.TrustScoreR\x06scores\"N\n" +
	"\x16ResetTrustScoreRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\"V\n" +
	"\x17ResetTrustScoreResponse\x12;\n" +
	"\x05score\x18\x01 \x01(\v2%.muxcore.playback.guard.v1.TrustScoreR\x05score\"\xb3\x01\n" +
	"\x11MergeUsersRequest\x12$\n" +
	"\x0esource_user_id\x18\x01 \x01(\tR\fsourceUserId\x12(\n" +
	"\x10source_user_name\x18\x02 \x01(\tR\x0esourceUserName\x12$\n" +
	"\x0etarget_user_id\x18\x03 \x01(\tR\ftargetUserId\x12(\n" +
	"\x10target_user_name\x18\x04 \x01(\tR\x0etargetUserName\"\x97\x01\n" +
	"\x12MergeUsersResponse\x12-\n" +
	"\x12violations_updated\x18\x01 \x01(\x05R\x11violationsUpdated\x12'\n" +
	"\x0faliases_created\x18\x02 \x01(\x05R\x0ealiasesCreated\x12)\n" +
	"\x10sessions_updated\x18\x03 \x01(\x05R\x0fsessionsUpdated*\xee\x01\n" +
	"\bRuleType\x12\x19\n" +
	"\x15RULE_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bRULE_TYPE_IMPOSSIBLE_TRAVEL\x10\x01\x12$\n" +
	" RULE_TYPE_SIMULTANEOUS_LOCATIONS\x10\x02\x12\x1d\n" +
	"\x19RULE_TYPE_DEVICE_VELOCITY\x10\x03\x12 \n" +
	"\x1cRULE_TYPE_CONCURRENT_STREAMS\x10\x04\x12\x1d\n" +
	"\x19RULE_TYPE_GEO_RESTRICTION\x10\x05\x12 \n" +
	"\x1cRULE_TYPE_ACCOUNT_INACTIVITY\x10\x062\xa8\t\n" +
	"\x14PlaybackGuardService\x12f\n" +
	"\tListRules\x12+.muxcore.playback.guard.v1.ListRulesRequest\x1a,.muxcore.playback.guard.v1.ListRulesResponse\x12i\n" +
	"\n" +
	"UpsertRule\x12,.muxcore.playback.guard.v1.UpsertRuleRequest\x1a-.muxcore.playback.guard.v1.UpsertRuleResponse\x12i\n" +
	"\n" +
	"DeleteRule\x12,.muxcore.playback.guard.v1.DeleteRuleRequest\x1a-.muxcore.playback.guard.v1.DeleteRuleResponse\x12u\n" +
	"\x0eListViolations\x120.muxcore.playback.guard.v1.ListViolationsRequest\x1a1.muxcore.playback.guard.v1.ListViolationsResponse\x12\x8a\x01\n" +
	"\x15AcknowledgeViolations\x127.muxcore.playback.guard.v1.AcknowledgeViolationsRequest\x1a8.muxcore.playback.guard.v1.AcknowledgeViolationsResponse\x12{\n" +
	"\x10TerminateSession\x122.muxcore.playback.guard.v1.TerminateSessionRequest\x1a3.muxcore.playback.guard.v1.TerminateSessionResponse\x12r\n" +
	"\rGetTrustScore\x12/.muxcore.playback.guard.v1.GetTrustScoreRequest\x1a0.muxcore.playback.guard.v1.GetTrustScoreResponse\x12x\n" +
	"\x0fListTrustScores\x121.muxcore.playback.guard.v1.ListTrustScoresRequest\x1a2.muxcore.playback.guard.v1.ListTrustScoresResponse\x12x\n" +
	"\x0fResetTrustScore\x121.muxcore.playback.guard.v1.ResetTrustScoreRequest\x1a2.muxcore.playback.guard.v1.ResetTrustScoreResponse\x12i\n" +
	"\n" +
	"MergeUsers\x12,.muxcore.playback.guard.v1.MergeUsersRequest\x1a-.muxcore.playback.guard.v1.MergeUsersResponseB?Z=github.com/Muxcore-Media/playback-guard/proto/guardv1;guardv1b\x06proto3"

var (
	file_proto_guardv1_guard_proto_rawDescOnce sync.Once
	file_proto_guardv1_guard_proto_rawDescData []byte
)

func file_proto_guardv1_guard_proto_rawDescGZIP() []byte {
	file_proto_guardv1_guard_proto_rawDescOnce.Do(func() {
		file_proto_guardv1_guard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_guardv1_guard_proto_rawDesc), len(file_proto_guardv1_guard_proto_rawDesc)))
	})
	return file_proto_guardv1_guard_proto_rawDescData
}

var file_proto_guardv1_guard_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_guardv1_guard_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_guardv1_guard_proto_goTypes = []any{
	(RuleType)(0),                         // 0: muxcore.playback.guard.v1.RuleType
	(*GuardRule)(nil),                     // 1: muxcore.playback.guard.v1.GuardRule
	(*Violation)(nil),                     // 2: muxcore.playback.guard.v1.Violation
	(*ListRulesRequest)(nil),              // 3: muxcore.playback.guard.v1.ListRulesRequest
	(*ListRulesResponse)(nil),             // 4: muxcore.playback.guard.v1.ListRulesResponse
	(*UpsertRuleRequest)(nil),             // 5: muxcore.playback.guard.v1.UpsertRuleRequest
	(*UpsertRuleResponse)(nil),            // 6: muxcore.playback.guard.v1.UpsertRuleResponse
	(*DeleteRuleRequest)(nil),             // 7: muxcore.playback.guard.v1.DeleteRuleRequest
	(*DeleteRuleResponse)(nil),            // 8: muxcore.playback.guard.v1.DeleteRuleResponse
	(*ListViolationsRequest)(nil),         // 9: muxcore.playback.guard.v1.ListViolationsRequest
	(*ListViolationsResponse)(nil),        // 10: muxcore.playback.guard.v1.ListViolationsResponse
	(*AcknowledgeViolationsRequest)(nil),  // 11: muxcore.playback.guard.v1.AcknowledgeViolationsRequest
	(*AcknowledgeViolationsResponse)(nil), // 12: muxcore.playback.guard.v1.AcknowledgeViolationsResponse
	(*TerminateSessionRequest)(nil),       // 13: muxcore.playback.guard.v1.TerminateSessionRequest
	(*TerminateSessionResponse)(nil),      // 14: muxcore.playback.guard.v1.TerminateSessionResponse
	(*TrustScore)(nil),                    // 15: muxcore.playback.guard.v1.TrustScore
	(*GetTrustScoreRequest)(nil),          // 16: muxcore.playback.guard.v1.GetTrustScoreRequest
	(*GetTrustScoreResponse)(nil),         // 17: muxcore.playback.guard.v1.GetTrustScoreResponse
	(*ListTrustScoresRequest)(nil),        // 18: muxcore.playback.guard.v1.ListTrustScoresRequest
	(*ListTrustScoresResponse)(nil),       // 19: muxcore.playback.guard.v1.ListTrustScoresResponse
	(*ResetTrustScoreRequest)(nil),        // 20: muxcore.playback.guard.v1.ResetTrustScoreRequest
	(*ResetTrustScoreResponse)(nil),       // 21: muxcore.playback.guard.v1.ResetTrustScoreResponse
	(*MergeUsersRequest)(nil),             // 22: muxcore.playback.guard.v1.MergeUsersRequest
	(*MergeUsersResponse)(nil),            // 23: muxcore.playback.guard.v1.MergeUsersResponse
	nil,                                   // 24: muxcore.playback.guard.v1.GuardRule.ParamsEntry
}
var file_proto_guardv1_guard_proto_depIdxs = []int32{
	0,  // 0: muxcore.playback.guard.v1.GuardRule.type:type_name -> muxcore.playback.guard.v1.RuleType
	24, // 1: muxcore.playback.guard.v1.GuardRule.params:type_name -> muxcore.playback.guard.v1.GuardRule.ParamsEntry
	0,  // 2: muxcore.playback.guard.v1.Violation.rule_type:type_name -> muxcore.playback.guard.v1.RuleType
	1,  // 3: muxcore.playback.guard.v1.ListRulesResponse.rules:type_name -> muxcore.playback.guard.v1.GuardRule
	1,  // 4: muxcore.playback.guard.v1.UpsertRuleRequest.rule:type_name -> muxcore.playback.guard.v1.GuardRule
	1,  // 5: muxcore.playback.guard.v1.UpsertRuleResponse.rule:type_name -> muxcore.playback.guard.v1.GuardRule
	2,  // 6: muxcore.playback.guard.v1.ListViolationsResponse.violations:type_name -> muxcore.playback.guard.v1.Violation
	15, // 7: muxcore.playback.guard.v1.GetTrustScoreResponse.score:type_name -> muxcore.playback.guard.v1.TrustScore
	15, // 8: muxcore.playback.guard.v1.ListTrustScoresResponse.scores:type_name -> muxcore.playback.guard.v1.TrustScore
	15, // 9: muxcore.playback.guard.v1.ResetTrustScoreResponse.score:type_name -> muxcore.playback.guard.v1.TrustScore
	3,  // 10: muxcore.playback.guard.v1.PlaybackGuardService.ListRules:input_type -> muxcore.playback.guard.v1.ListRulesRequest
	5,  // 11: muxcore.playback.guard.v1.PlaybackGuardService.UpsertRule:input_type -> muxcore.playback.guard.v1.UpsertRuleRequest
	7,  // 12: muxcore.playback.guard.v1.PlaybackGuardService.DeleteRule:input_type -> muxcore.playback.guard.v1.DeleteRuleRequest
	9,  // 13: muxcore.playback.guard.v1.PlaybackGuardService.ListViolations:input_type -> muxcore.playback.guard.v1.ListViolationsRequest
	11, // 14: muxcore.playback.guard.v1.PlaybackGuardService.AcknowledgeViolations:input_type -> muxcore.playback.guard.v1.AcknowledgeViolationsRequest
	13, // 15: muxcore.playback.guard.v1.PlaybackGuardService.TerminateSession:input_type -> muxcore.playback.guard.v1.TerminateSessionRequest
	16, // 16: muxcore.playback.guard.v1.PlaybackGuardService.GetTrustScore:input_type -> muxcore.playback.guard.v1.GetTrustScoreRequest
	18, // 17: muxcore.playback.guard.v1.PlaybackGuardService.ListTrustScores:input_type -> muxcore.playback.guard.v1.ListTrustScoresRequest
	20, // 18: muxcore.playback.guard.v1.PlaybackGuardService.ResetTrustScore:input_type -> muxcore.playback.guard.v1.ResetTrustScoreRequest
	22, // 19: muxcore.playback.guard.v1.PlaybackGuardService.MergeUsers:input_type -> muxcore.playback.guard.v1.MergeUsersRequest
	4,  // 20: muxcore.playback.guard.v1.PlaybackGuardService.ListRules:output_type -> muxcore.playback.guard.v1.ListRulesResponse
	6,  // 21: muxcore.playback.guard.v1.PlaybackGuardService.UpsertRule:output_type -> muxcore.playback.guard.v1.UpsertRuleResponse
	8,  // 22: muxcore.playback.guard.v1.PlaybackGuardService.DeleteRule:output_type -> muxcore.playback.guard.v1.DeleteRuleResponse
	10, // 23: muxcore.playback.guard.v1.PlaybackGuardService.ListViolations:output_type -> muxcore.playback.guard.v1.ListViolationsResponse
	12, // 24: muxcore.playback.guard.v1.PlaybackGuardService.AcknowledgeViolations:output_type -> muxcore.playback.guard.v1.AcknowledgeViolationsResponse
	14, // 25: muxcore.playback.guard.v1.PlaybackGuardService.TerminateSession:output_type -> muxcore.playback.guard.v1.TerminateSessionResponse
	17, // 26: muxcore.playback.guard.v1.PlaybackGuardService.GetTrustScore:output_type -> muxcore.playback.guard.v1.GetTrustScoreResponse
	19, // 27: muxcore.playback.guard.v1.PlaybackGuardService.ListTrustScores:output_type -> muxcore.playback.guard.v1.ListTrustScoresResponse
	21, // 28: muxcore.playback.guard.v1.PlaybackGuardService.ResetTrustScore:output_type -> muxcore.playback.guard.v1.ResetTrustScoreResponse
	23, // 29: muxcore.playback.guard.v1.PlaybackGuardService.MergeUsers:output_type -> muxcore.playback.guard.v1.MergeUsersResponse
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_guardv1_guard_proto_init() }
func file_proto_guardv1_guard_proto_init() {
	if File_proto_guardv1_guard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_guardv1_guard_proto_rawDesc), len(file_proto_guardv1_guard_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_guardv1_guard_proto_goTypes,
		DependencyIndexes: file_proto_guardv1_guard_proto_depIdxs,
		EnumInfos:         file_proto_guardv1_guard_proto_enumTypes,
		MessageInfos:      file_proto_guardv1_guard_proto_msgTypes,
	}.Build()
	File_proto_guardv1_guard_proto = out.File
	file_proto_guardv1_guard_proto_goTypes = nil
	file_proto_guardv1_guard_proto_depIdxs = nil
}
