// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/guardv1/guard.proto

package guardv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlaybackGuardService_ListRules_FullMethodName             = "/muxcore.playback.guard.v1.PlaybackGuardService/ListRules"
	PlaybackGuardService_UpsertRule_FullMethodName            = "/muxcore.playback.guard.v1.PlaybackGuardService/UpsertRule"
	PlaybackGuardService_DeleteRule_FullMethodName            = "/muxcore.playback.guard.v1.PlaybackGuardService/DeleteRule"
	PlaybackGuardService_ListViolations_FullMethodName        = "/muxcore.playback.guard.v1.PlaybackGuardService/ListViolations"
	PlaybackGuardService_AcknowledgeViolations_FullMethodName = "/muxcore.playback.guard.v1.PlaybackGuardService/AcknowledgeViolations"
	PlaybackGuardService_TerminateSession_FullMethodName      = "/muxcore.playback.guard.v1.PlaybackGuardService/TerminateSession"
	PlaybackGuardService_GetTrustScore_FullMethodName         = "/muxcore.playback.guard.v1.PlaybackGuardService/GetTrustScore"
	PlaybackGuardService_ListTrustScores_FullMethodName       = "/muxcore.playback.guard.v1.PlaybackGuardService/ListTrustScores"
	PlaybackGuardService_ResetTrustScore_FullMethodName       = "/muxcore.playback.guard.v1.PlaybackGuardService/ResetTrustScore"
	PlaybackGuardService_MergeUsers_FullMethodName            = "/muxcore.playback.guard.v1.PlaybackGuardService/MergeUsers"
)

// PlaybackGuardServiceClient is the client API for PlaybackGuardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlaybackGuardServiceClient interface {
	ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error)
	UpsertRule(ctx context.Context, in *UpsertRuleRequest, opts ...grpc.CallOption) (*UpsertRuleResponse, error)
	DeleteRule(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*DeleteRuleResponse, error)
	ListViolations(ctx context.Context, in *ListViolationsRequest, opts ...grpc.CallOption) (*ListViolationsResponse, error)
	AcknowledgeViolations(ctx context.Context, in *AcknowledgeViolationsRequest, opts ...grpc.CallOption) (*AcknowledgeViolationsResponse, error)
	TerminateSession(ctx context.Context, in *TerminateSessionRequest, opts ...grpc.CallOption) (*TerminateSessionResponse, error)
	GetTrustScore(ctx context.Context, in *GetTrustScoreRequest, opts ...grpc.CallOption) (*GetTrustScoreResponse, error)
	ListTrustScores(ctx context.Context, in *ListTrustScoresRequest, opts ...grpc.CallOption) (*ListTrustScoresResponse, error)
	ResetTrustScore(ctx context.Context, in *ResetTrustScoreRequest, opts ...grpc.CallOption) (*ResetTrustScoreResponse, error)
	MergeUsers(ctx context.Context, in *MergeUsersRequest, opts ...grpc.CallOption) (*MergeUsersResponse, error)
}

type playbackGuardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlaybackGuardServiceClient(cc grpc.ClientConnInterface) PlaybackGuardServiceClient {
	return &playbackGuardServiceClient{cc}
}

func (c *playbackGuardServiceClient) ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRulesResponse)
	err := c.cc.Invoke(ctx, PlaybackGuardService_ListRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackGuardServiceClient) UpsertRule(ctx context.Context, in *UpsertRuleRequest, opts ...grpc.CallOption) (*UpsertRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertRuleResponse)
	err := c.cc.Invoke(ctx, PlaybackGuardService_UpsertRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackGuardServiceClient) DeleteRule(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*DeleteRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRuleResponse)
	err := c.cc.Invoke(ctx, PlaybackGuardService_DeleteRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackGuardServiceClient) ListViolations(ctx context.Context, in *ListViolationsRequest, opts ...grpc.CallOption) (*ListViolationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListViolationsResponse)
	err := c.cc.Invoke(ctx, PlaybackGuardService_ListViolations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackGuardServiceClient) AcknowledgeViolations(ctx context.Context, in *AcknowledgeViolationsRequest, opts ...grpc.CallOption) (*AcknowledgeViolationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeViolationsResponse)
	err := c.cc.Invoke(ctx, PlaybackGuardService_AcknowledgeViolations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackGuardServiceClient) TerminateSession(ctx context.Context, in *TerminateSessionRequest, opts ...grpc.CallOption) (*TerminateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateSessionResponse)
	err := c.cc.Invoke(ctx, PlaybackGuardService_TerminateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackGuardServiceClient) GetTrustScore(ctx context.Context, in *GetTrustScoreRequest, opts ...grpc.CallOption) (*GetTrustScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrustScoreResponse)
	err := c.cc.Invoke(ctx, PlaybackGuardService_GetTrustScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackGuardServiceClient) ListTrustScores(ctx context.Context, in *ListTrustScoresRequest, opts ...grpc.CallOption) (*ListTrustScoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTrustScoresResponse)
	err := c.cc.Invoke(ctx, PlaybackGuardService_ListTrustScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackGuardServiceClient) ResetTrustScore(ctx context.Context, in *ResetTrustScoreRequest, opts ...grpc.CallOption) (*ResetTrustScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetTrustScoreResponse)
	err := c.cc.Invoke(ctx, PlaybackGuardService_ResetTrustScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackGuardServiceClient) MergeUsers(ctx context.Context, in *MergeUsersRequest, opts ...grpc.CallOption) (*MergeUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeUsersResponse)
	err := c.cc.Invoke(ctx, PlaybackGuardService_MergeUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaybackGuardServiceServer is the server API for PlaybackGuardService service.
// All implementations must embed UnimplementedPlaybackGuardServiceServer
// for forward compatibility.
type PlaybackGuardServiceServer interface {
	ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error)
	UpsertRule(context.Context, *UpsertRuleRequest) (*UpsertRuleResponse, error)
	DeleteRule(context.Context, *DeleteRuleRequest) (*DeleteRuleResponse, error)
	ListViolations(context.Context, *ListViolationsRequest) (*ListViolationsResponse, error)
	AcknowledgeViolations(context.Context, *AcknowledgeViolationsRequest) (*AcknowledgeViolationsResponse, error)
	TerminateSession(context.Context, *TerminateSessionRequest) (*TerminateSessionResponse, error)
	GetTrustScore(context.Context, *GetTrustScoreRequest) (*GetTrustScoreResponse, error)
	ListTrustScores(context.Context, *ListTrustScoresRequest) (*ListTrustScoresResponse, error)
	ResetTrustScore(context.Context, *ResetTrustScoreRequest) (*ResetTrustScoreResponse, error)
	MergeUsers(context.Context, *MergeUsersRequest) (*MergeUsersResponse, error)
	mustEmbedUnimplementedPlaybackGuardServiceServer()
}

// UnimplementedPlaybackGuardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlaybackGuardServiceServer struct{}

func (UnimplementedPlaybackGuardServiceServer) ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRules not implemented")
}
func (UnimplementedPlaybackGuardServiceServer) UpsertRule(context.Context, *UpsertRuleRequest) (*UpsertRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertRule not implemented")
}
func (UnimplementedPlaybackGuardServiceServer) DeleteRule(context.Context, *DeleteRuleRequest) (*DeleteRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRule not implemented")
}
func (UnimplementedPlaybackGuardServiceServer) ListViolations(context.Context, *ListViolationsRequest) (*ListViolationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListViolations not implemented")
}
func (UnimplementedPlaybackGuardServiceServer) AcknowledgeViolations(context.Context, *AcknowledgeViolationsRequest) (*AcknowledgeViolationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeViolations not implemented")
}
func (UnimplementedPlaybackGuardServiceServer) TerminateSession(context.Context, *TerminateSessionRequest) (*TerminateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateSession not implemented")
}
func (UnimplementedPlaybackGuardServiceServer) GetTrustScore(context.Context, *GetTrustScoreRequest) (*GetTrustScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrustScore not implemented")
}
func (UnimplementedPlaybackGuardServiceServer) ListTrustScores(context.Context, *ListTrustScoresRequest) (*ListTrustScoresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrustScores not implemented")
}
func (UnimplementedPlaybackGuardServiceServer) ResetTrustScore(context.Context, *ResetTrustScoreRequest) (*ResetTrustScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetTrustScore not implemented")
}
func (UnimplementedPlaybackGuardServiceServer) MergeUsers(context.Context, *MergeUsersRequest) (*MergeUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MergeUsers not implemented")
}
func (UnimplementedPlaybackGuardServiceServer) mustEmbedUnimplementedPlaybackGuardServiceServer() {}
func (UnimplementedPlaybackGuardServiceServer) testEmbeddedByValue()                              {}

// UnsafePlaybackGuardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlaybackGuardServiceServer will
// result in compilation errors.
type UnsafePlaybackGuardServiceServer interface {
	mustEmbedUnimplementedPlaybackGuardServiceServer()
}

func RegisterPlaybackGuardServiceServer(s grpc.ServiceRegistrar, srv PlaybackGuardServiceServer) {
	// If the following call panics, it indicates UnimplementedPlaybackGuardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlaybackGuardService_ServiceDesc, srv)
}

func _PlaybackGuardService_ListRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackGuardServiceServer).ListRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackGuardService_ListRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackGuardServiceServer).ListRules(ctx, req.(*ListRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackGuardService_UpsertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackGuardServiceServer).UpsertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackGuardService_UpsertRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackGuardServiceServer).UpsertRule(ctx, req.(*UpsertRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackGuardService_DeleteRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackGuardServiceServer).DeleteRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackGuardService_DeleteRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackGuardServiceServer).DeleteRule(ctx, req.(*DeleteRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackGuardService_ListViolations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListViolationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackGuardServiceServer).ListViolations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackGuardService_ListViolations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackGuardServiceServer).ListViolations(ctx, req.(*ListViolationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackGuardService_AcknowledgeViolations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeViolationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackGuardServiceServer).AcknowledgeViolations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackGuardService_AcknowledgeViolations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackGuardServiceServer).AcknowledgeViolations(ctx, req.(*AcknowledgeViolationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackGuardService_TerminateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackGuardServiceServer).TerminateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackGuardService_TerminateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackGuardServiceServer).TerminateSession(ctx, req.(*TerminateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackGuardService_GetTrustScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrustScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackGuardServiceServer).GetTrustScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackGuardService_GetTrustScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackGuardServiceServer).GetTrustScore(ctx, req.(*GetTrustScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackGuardService_ListTrustScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrustScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackGuardServiceServer).ListTrustScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackGuardService_ListTrustScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackGuardServiceServer).ListTrustScores(ctx, req.(*ListTrustScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackGuardService_ResetTrustScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetTrustScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackGuardServiceServer).ResetTrustScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackGuardService_ResetTrustScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackGuardServiceServer).ResetTrustScore(ctx, req.(*ResetTrustScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackGuardService_MergeUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackGuardServiceServer).MergeUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackGuardService_MergeUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackGuardServiceServer).MergeUsers(ctx, req.(*MergeUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlaybackGuardService_ServiceDesc is the grpc.ServiceDesc for PlaybackGuardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlaybackGuardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muxcore.playback.guard.v1.PlaybackGuardService",
	HandlerType: (*PlaybackGuardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRules",
			Handler:    _PlaybackGuardService_ListRules_Handler,
		},
		{
			MethodName: "UpsertRule",
			Handler:    _PlaybackGuardService_UpsertRule_Handler,
		},
		{
			MethodName: "DeleteRule",
			Handler:    _PlaybackGuardService_DeleteRule_Handler,
		},
		{
			MethodName: "ListViolations",
			Handler:    _PlaybackGuardService_ListViolations_Handler,
		},
		{
			MethodName: "AcknowledgeViolations",
			Handler:    _PlaybackGuardService_AcknowledgeViolations_Handler,
		},
		{
			MethodName: "TerminateSession",
			Handler:    _PlaybackGuardService_TerminateSession_Handler,
		},
		{
			MethodName: "GetTrustScore",
			Handler:    _PlaybackGuardService_GetTrustScore_Handler,
		},
		{
			MethodName: "ListTrustScores",
			Handler:    _PlaybackGuardService_ListTrustScores_Handler,
		},
		{
			MethodName: "ResetTrustScore",
			Handler:    _PlaybackGuardService_ResetTrustScore_Handler,
		},
		{
			MethodName: "MergeUsers",
			Handler:    _PlaybackGuardService_MergeUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/guardv1/guard.proto",
}
